export type Listing={id:string;title:string;price:number;city:string;region:string;category:string;image:string;condition:string;time:string;verified?:boolean;description:string};
export const categories=[['🚗','მან?','መኪናዎች','Cars'],['🏠','ቤቶች','ቤት እና መሬት','Real estate'],['💻','ኤሌክትሮኒክስ','ኤሌክትሮኒክስ','Electronics'],['🛋️','የቤት ዕቃ','የቤት ዕቃ','Furniture'],['💼','ስራ','ስራ እና አገልግሎት','Jobs'],['🛠️','አገልግሎት','አገልግሎት','Services'],['🐕','እንስሳት','እንስሳት','Animals'],['📱','ስልኮች','ስልኮች','Phones']];
export const cities=['Addis Ababa','Bahir Dar','Hawassa','Dire Dawa','Mekelle','Adama','Jimma','Gondar','Bishoftu','Dessie'];
export const listings:Listing[]=[
{id:'1',title:'Toyota Land Cruiser Prado 2021',price:6850000,city:'Addis Ababa',region:'Oromia',category:'Cars',image:'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?auto=format&fit=crop&w=1200&q=82',condition:'Used',time:'18 min ago',verified:true,description:'Well maintained Prado with clean interior, service history and complete paperwork. Serious buyers only.'},
{id:'2',title:'Modern 3 bedroom apartment — Bole',price:14500000,city:'Addis Ababa',region:'Addis Ababa',category:'Real estate',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=82',condition:'New',time:'42 min ago',verified:true,description:'Bright modern apartment in a secure compound near Bole. Parking, elevator and 24/7 security.'},
{id:'3',title:'iPhone 15 Pro Max 256GB',price:98000,city:'Addis Ababa',region:'Addis Ababa',category:'Phones',image:'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&w=1200&q=82',condition:'Like new',time:'1 hr ago',verified:true,description:'Genuine device, lightly used, battery health 99%. Box and accessories included.'},
{id:'4',title:'Samsung 55” Neo QLED Smart TV',price:125000,city:'Bahir Dar',region:'Amhara',category:'Electronics',image:'https://images.unsplash.com/photo-1593784991095-a205069470b6?auto=format&fit=crop&w=1200&q=82',condition:'New',time:'2 hrs ago',description:'Factory sealed 55-inch Samsung Neo QLED. Delivery available within Bahir Dar.'},
{id:'5',title:'Office desk + ergonomic chair set',price:42000,city:'Hawassa',region:'Sidama',category:'Furniture',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=82',condition:'Used',time:'3 hrs ago',description:'Solid wood desk with ergonomic chair. Great for a home office or small studio.'},
{id:'6',title:'Toyota Hiace 2018 — 16 seat',price:3650000,city:'Adama',region:'Oromia',category:'Cars',image:'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=82',condition:'Used',time:'4 hrs ago',description:'Reliable Hiace, clean title and recently serviced. Ready for business use.'},
{id:'7',title:'Commercial shop — Mexico area',price:7200000,city:'Addis Ababa',region:'Addis Ababa',category:'Real estate',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=82',condition:'New',time:'5 hrs ago',description:'Street-facing commercial space with high foot traffic and flexible lease terms.'},
{id:'8',title:'MacBook Air M3 15-inch',price:145000,city:'Addis Ababa',region:'Addis Ababa',category:'Electronics',image:'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=82',condition:'Like new',time:'6 hrs ago',verified:true,description:'M3 MacBook Air, 16GB RAM, 512GB SSD. Original charger and box.'}
];
export const money=(n:number)=>new Intl.NumberFormat('en-US').format(n)+' ETB';
